const DEFAULT_ITEMS_PER_PAGE = 7;
const DEFAULT_ITEMS_PER_TABLE = 10;
const FIRST_PAGE = 1;
const INITIAL_TOTAL_ITEMS = 0;

export {
  DEFAULT_ITEMS_PER_PAGE,
  FIRST_PAGE,
  INITIAL_TOTAL_ITEMS,
  DEFAULT_ITEMS_PER_TABLE,
};
