const DEFAULT_VALUE = 7;
const MILLISECONDS = 1000;
const LEFT_CAR_POSITION = 140;
const INITIAL_TOTAL_ITEMS = 0;
const START_POSITION = 0;
const LENGTH_OF_NAME = 15;

export {
  DEFAULT_VALUE,
  MILLISECONDS,
  LEFT_CAR_POSITION,
  INITIAL_TOTAL_ITEMS,
  START_POSITION,
  LENGTH_OF_NAME,
};
