const DEFAULT_PLACEHOLDER = '';
const DEFAULT_COLOR = '#336b87';
const DEFAULT_VALUE_NAME = '';
const NEW_VALUE = 'New Car';
const INITIAL_TOTAL_ITEMS = 0;

export {
  DEFAULT_PLACEHOLDER,
  DEFAULT_COLOR,
  DEFAULT_VALUE_NAME,
  NEW_VALUE,
  INITIAL_TOTAL_ITEMS,
};
